{
  imports = [
    ./lualine.nix
    ./telescope.nix
    ./web-devicons.nix
    ./treesitter.nix
    ./neo-tree.nix
    ./lsp.nix
    ./blink-cmp.nix
    ./none-ls.nix
    ./hop.nix
    ./comment.nix
    ./friendly-snippets.nix
    ./barbar.nix
    ./autopairs.nix
    ./blame_line.nix
    ./alpha.nix
    ./gitsigns.nix
    ./visual-multi.nix
    ./lazygit.nix
    ./better-escape.nix
    ./yanky.nix
  ];
}
